[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"    # `anchor-cli` version to use(requires `avm`)
solana_version = "3.0.13"    # Solana version to use(applies to all Solana tools)

[features]
resolution = true
skip-lint = false

[programs.localnet]
cascade = "HQ8ejrFMtoNsShZRqkH842BRDqpzh7Xy7b5iqc1U9ffA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run tsx --test --test-reporter=spec tests/*.ts"
